spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
server:
  port: 8081
beerapi:
  url: http://webapp-rest-api:8082